### ISSUE TITLE
Forced development environment and support for variables in queries (server)

### ISSUE THREAD

**Issue by droidpl** [mondaycom/monday-sdk-js#1]
No matter what is set in the `NODE_ENV` environment variable, it fails to use the SDK as it has hardcoded a non-existend url. See the line referenced in the link below:

https://github.com/DaPulse/monday-sdk/blob/86a59412a9a9d523a73de1a19a2ab31b110e09d3/src/constants.js#L3

Also I think setting this as a `process.env.NODE_ENV` is not a good idea since it takes whatever the user is using in his environment. I think it would be good to use a parameter or always stick to the public API as part of the sdk.

**Comment by omerdoron1** [comment]
@droidpl we've fixed it. Now the SDK will always stick to the public API.

**Comment by droidpl** [comment]
Great thanks. Is there a big difference in usage from the previous one? I am using it to query and mutate and would like to know if it still supports the same methods/api. Also if it includes the variable parsing in the queries
