### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by DanielNetzeriAm** [mondaycom/monday-sdk-js#27]
Well the problem it's solving is pretty obvious, we get proper typings for everything pretty much :D

A good implemention will cover all GQL schemas as types, obviously the SDK core functionality typed.
there's some very good tools to achieve that such as https://www.npmjs.com/package/graphql-schema-typescript

At the moment even initializing the SDK itself is complicated and errors aren't thrown back to the consumer which makes things near impossible to debug.

**Comment by josh-** [comment]
Hey @danielmittelman :wave: I'm not associated with the project but I'd also like to use it with TypeScript, so I've started work on some type definitions here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46311

Currently doesn't contain the GQL schema but I've covered most of the documented functionality.

**Comment by vladmonday** [comment]
Hey @DanielNetzeriAm, 
For now, we don't have in our roadmap plans to add TS support, but this project is open-source, so you can create a PR with TS definitions and we will be happy to merge your contribution!

**Comment by kaminskypavel** [comment]
I have a generated **unofficial** schema I can share if interested
