### ISSUE TITLE
documentation lack some info

### ISSUE THREAD

**Issue by yureckey** [mondaycom/monday-sdk-js#28]
in the Monday.com official sdk doc pages
https://monday.com/developers/apps/sdk
and https://github.com/mondaycom/monday-sdk-js readme.md I can't find mentions of some functions I see on 
https://monday.com/developers/apps/advanced-view
in particular 
monday.execute("confirm", options)
monday.execute("notice", options)

**Comment by vladmonday** [comment]
Hey @yureckey , the documentation was updated, it includes now "confirm" and "execute" functions.
Thanks!
