### ISSUE TITLE
Create Dropdown with default labels 

### ISSUE THREAD

**Issue by mitul69** [mondaycom/monday-sdk-js#29]
**Describe the bug**
I want to create drop down with default options, I have tried with defaults option but not working.

**Steps to reproduce**
1. Embed the SDK in an app
2. Call `mutation {
  create_column(board_id: <bordId>, title: "DropDown 3", column_type: dropdown, defaults: "{\"labels\":[\"My label\"]}") {
    id
  }
}
`
3. See the request fails
4. Only create column without any default label 

**Expected behavior**
There should be new column with default value which passed in default labels

**Comment by vladmonday** [comment]
Follow up in this community conversation
