### ISSUE TITLE
Create new workspace.

### ISSUE THREAD

**Issue by mitul69** [mondaycom/monday-sdk-js#30]
**What problem is this request going to solve?**
I want to create new workspace using api can you please create new mutation for the create workspace

**What is the solution you'd like to see?**
Create new mutation for the workspace.

**Describe alternatives you've considered**
Yes not working 

**Additional information**

**Comment by vladmonday** [comment]
Hey @mitul69 
We are considering adding workspace support to the API in the near future, will keep you posted!

**Comment by vladmonday** [comment]
Hey @mitul69, we release the new API mutation for creating workspaces, you can use it now.
Thanks!
https://monday.com/developers/v2#mutations-section-workspaces-create
