### ISSUE TITLE
Update Column

### ISSUE THREAD

**Issue by mitul69** [mondaycom/monday-sdk-js#31]
**What problem is this request going to solve?**
Can you please provide feature for update column title using mutation. 

**What is the solution you'd like to see?**
There will be way to update the column title using mutation 

**Describe alternatives you've considered**

**Additional information**

**Comment by vladmonday** [comment]
Hey @mitul69,
Right now we don't have a plan of adding this API mutation, but you can raise this topic in the API Feature Requests community thread (https://community.monday.com/c/developers/api-feature-requests/58) and if more people will vote for this feature, it will be added to our roadmap.

Thanks
