### ISSUE TITLE
Get Column Details

### ISSUE THREAD

**Issue by mitul69** [mondaycom/monday-sdk-js#32]
**What problem is this request going to solve?**
Can you please provide a value of the description while querying the values for the column

**What is the solution you'd like to see?**
It will return the column description for while we fetch the column details 

**Describe alternatives you've considered**

**Additional information**

**Comment by vladmonday** [comment]
Hey @mitul69,
Right now we don't have a plan of adding a description field to the Column query, but you can raise this topic in the API Feature Requests community thread (https://community.monday.com/c/developers/api-feature-requests/58) and if more people will vote for this feature, it will be added to our roadmap.
