### ISSUE TITLE
[Feature] Strip extra whitespace from payload before sending requests

### ISSUE THREAD

**Issue by Spunkie** [mondaycom/monday-sdk-js#35]
**What problem is this request going to solve?**
The SDK is sending a bunch of unnecessary whitespace in the request payload when making api calls. Which in our specific use case is a bunch of extra `\t` indentation characters from graphql code.

**What is the solution you'd like to see?**
The SDK should automatically strip out all superfluous characters before sending a payload. Those characters being things like spaces, tabs, return line chars, end of line chars, other whitespace chars, and commented out graphql lines.

**Comment by Spunkie** [comment]
To follow up on this, we solve this in our app at build time with [frontendr/babel-plugin-transform-compress-graphql](https://github.com/frontendr/babel-plugin-transform-compress-graphql),  [jaydenseric/fake-tag](https://github.com/jaydenseric/fake-tag), and prepending our graphql string literals with `gql`.

Rough example code:
````javascript
import gql from 'fake-tag'
import mondaySdk from "monday-sdk-js";
const monday = mondaySdk();

const {
	data: { users },
} = await monday.api(gql`
	query {
		users(ids: [${this.users}]) {
			id
			name
			photo_thumb_small
		}
	}
`)
````
Would become something like the following in production code post babel:
````javascript
import mondaySdk from "monday-sdk-js";
const monday = mondaySdk();

const {data:{users}} = await monday.api(`query{users(ids:[${this.users}]){id name photo_thumb_small}}`)
````
_Note: it won't really look like this since babel does a bunch of other shuffling around of code and minifying, but you get the point._ 
___
It still seems to me that there should be some kind of runtime solution included directly in `monday-sdk-js`. Whether that should be the full blow solution of [rse/graphql-query-compress](https://github.com/rse/graphql-query-compress) or a much simpler regex based solution like [jeromecovington/graphql-compress](https://github.com/jeromecovington/graphql-compress) I'm not sure.

**Comment by gregra81** [comment]
@Spunkie do you think it's worth merging it with https://github.com/mondaycom/monday-sdk-js/issues/82 and close this one?

**Comment by Spunkie** [comment]
> @Spunkie do you think it's worth merging it with #82 and close this one?

@gregra81 Unless you have a PR that address both, definitely not. 

#82 is related but may end up being fixed with a smaller patch server side/client side. In fact, if #82 is related to server side it should also be reported and addressed there instead of the sdk. A graphql server should not be rejecting whitespace.

While #35 is about the root code quality issue with the sdk, by default it just shouldn't be sending a bunch of junk escaped whitespace. It's wasted bytes across the wire and it makes the queries very hard to read or work with for debugging.

**Comment by gregra81** [comment]
Got it, thanks for the detailed explanation. ATM we do not want to invest additional efforts in the api part of the SDK, and instead planning to create a new typescript api only SDK that treats the api calls in a more native way. Stay tuned.

In the meantime, I'm closing this one, just for hygiene purposes.
