### ISSUE TITLE
[Bug] GraphQL exceptions are ignored and replaced with a generic "Graphql validation errors"

### ISSUE THREAD

**Issue by amitozalvo** [mondaycom/monday-sdk-js#41]
**Describe the bug**
When I exceed the maximum complexity, I don't get any error object that allows me to know that and retry.

**Steps to reproduce**
Call monday.api, exceed the maximum complexity, and you will get an unmeaningful error message "graphql validation errors" 

**Expected behavior**
Like the actual XHR request of the query, return me the error list.

**Comment by vladmonday** [comment]
Hey @amitozalvo, the issue is solved in the new 0.1.2 release (https://github.com/mondaycom/monday-sdk-js/releases/tag/0.1.2)
