### ISSUE TITLE
[Bug] Storage API Versioning

### ISSUE THREAD

**Issue by anderslyman** [mondaycom/monday-sdk-js#42]
**Describe the bug**
Storage API does not respect versioning

**Steps to reproduce**
Get something from storage:

```
this.mondayClientSdk.storage.instance.getItem(key).then(
    r => {
      const version = r.data.version;
      // Keep track of the version
    }
);
```
Store a new value:
```
this.mondayClientSdk.storage.instance.setItem(key, value).then(
  r => console.log(r),
  e => console.error(e)
);
```

Note that a _different_ version is now in stored.

Now try to store a new value using the version retrieved in the first snippet:
```
this.mondayClientSdk.storage.instance.setItem(key, value, {previous_version: version}).then(
  r => console.log(r),
  e => console.error(e)
);
```

This succeeds and _does not_ result in a `version_conflict` error as described in the docs.

**Expected behavior**
A `version_conflict` error.

**Comment by gregra81** [comment]
Hey @anderslyman. I know this is coming two and a half years later (we're doing some cleanup on our issues), but this one is resolved for some time

**Comment by anderslyman** [comment]
@gregra81 much appreciated, thank you!
