### ISSUE TITLE
[Bug] openItemCard keep refreshing the page

### ISSUE THREAD

**Issue by yarhuoy** [mondaycom/monday-sdk-js#45]
**Describe the bug**
https://www.loom.com/share/08678a1075ed4547a60af0699db87289

The button is triggering the following code:
`monday.execute('openItemCard', { itemId: 973937553 });`

As you can see in the video, when the popup open and close, the page behind the popup will refresh, this is causing serious performance issue to our custom app (the amount of our data is very large and it keep retrieving the data again and again), it wasn't like this before, can I know what is the problem?

Br, YarHuoy

**Comment by gregra81** [comment]
@yarhuoy I know this is coming two years after, but just FYI this no longer and issue
