### ISSUE TITLE
[Question] tutorial about how to embed custom html widget in monday to extend it? 

### ISSUE THREAD

**Issue by cesarpachon** [mondaycom/monday-sdk-js#52]
Hello my company recently subscribed to Monday, I am interested in learn how to develop a html/javascript widget to embed in the monday portal so we can integrate with other components of our platform.
I suspect this repo is the key but I wonder if there are examples or tutorials available. 
thanks!

**Comment by yuhgto** [comment]
Hey, not sure if this is still relevant, but our Docs Viewer sample app is what you're looking for. 

It shows you how to embed different platforms into a monday view. You can extend it to fit other use cases as well. 

Check it out here, in our welcome-apps repo: https://github.com/mondaycom/welcome-apps/tree/master/apps/docs-viewer
