### ISSUE TITLE
[Bug] Module "stream" has been externalized for browser compatibility and cannot be accessed in client code.

### ISSUE THREAD

**Issue by OnlyBjarne** [mondaycom/monday-sdk-js#54]
**Describe the bug**
Unable to import and use monday-sdk-js in a vue project using Vite as bundler.

**Steps to reproduce**
1. Create a new project using `npm init vue@next` (with Vite)
2. Install monday-sdk-js
3. import and initialize monday-sdk
4. Get error `Uncaught Error: Module "stream" has been externalized for browser compatibility and cannot be accessed in client code.`

**Expected behavior**
Expected to be able to import and use MondaySDK clientside

**Context and environment**
Vite, vue3, firefox

**Comment by gregra81** [comment]
Hey @OnlyBjarne, is this still reproducible for you?

**Comment by gregra81** [comment]
Closing this as I assume this was solved. Feel free to open a new issue in case you encounter a similar behavior
