### ISSUE TITLE
[Feature] Custom event triggering

### ISSUE THREAD

**Issue by Guichaguri** [mondaycom/monday-sdk-js#55]
**What problem is this request going to solve?**
In real-time applications, we have to use custom remote servers to trigger updates in all connected clients.

**What is the solution you'd like to see?**
Since Monday already has board events, it would be good if the app was able to trigger and listen to custom events.

The creation of a `trigger(eventName, metadata)` function that would work with the already existing `listen(eventName, listener)` function.

**Describe alternatives you've considered**
The main alternative is to use a custom websocket server, which would handle and broadcast events to all users connected to the view, but that depends relying on that external server in order to work.

**Comment by gregra81** [comment]
@Guichaguri What sort of events do you want to transmit to the connected clients? Are we talking about data changing on the boards on monday side or your app side?

**Comment by Guichaguri** [comment]
The original intent was in the app side. Since the SDK already has a few functions for storing and reading arbitrary per-app data, I thought sending events for synchronization purposes was not a big stretch.

For instance, apps like "planning poker" may use that feature so that all users with the app open see the votes happening in real time.

This feature would be useful for any kind of app that have some kind of real time collaboration feature, and it allows those to not have to rely on external servers but just the monday platform.

**Comment by gregra81** [comment]
@Guichaguri Got it. This request is not related to the SDK. You would like monday to provide you with a public API that supports web sockets for your app. Feel free to submit this feature request through our feature requests form here: https://support.monday.com/hc/en-us/requests/new?ticket_form_id=13855862562962.

In the meantime, I'm closing this one
