### ISSUE TITLE
[Bug] triggerFilesUpload Failing Partially

### ISSUE THREAD

**Issue by TheSecMaven** [mondaycom/monday-sdk-js#58]
**Describe the bug**
I am having a hard time using the triggerFilesUpload, I see the file in file gallery but only for a few minutes, then its gone. I also get an error in the console after the upload. I think it has to do with attaching the file to a column.

**Steps to reproduce**
1. Embed the SDK in an app
2. Call `            monday
              .execute("triggerFilesUpload", {
                boardId: boardId,
                itemId: fileres.data.create_item.id,
                columnId: "files",
              })
`
3. See the request succeeds initially but an error is logged in console and the file eventually is gone from file gallery in monday.com

**Expected behavior**
I'd expect the file to show up in the column ID I named, not just the gallery. I also expect it to persist. 

**Context and environment**
local app, google chrome latest version, latest version of the SDK

**Additional information**

**Comment by gregra81** [comment]
@TheSecMaven Is this still relevant?

**Comment by TheSecMaven** [comment]
No, I am not sure it works now or not but I found a workaround I think with the raw graphql API and using a backend process

**Comment by gregra81** [comment]
Great to hear, thanks
