### ISSUE TITLE
monday.oauthToken always fails 

### ISSUE THREAD

**Issue by ionscorobogaci** [mondaycom/monday-sdk-js#62]
**Describe the bug**
Using monday sdk on server side to exchange the code for an token fails with an empty error

**Steps to reproduce**
1. Embed the SDK in an app
2. Call `monday.oauthToken(
      "code",
      MONDAY_APP_CLIENT_ID,
      MONDAY_APP_CLIENT_SECRET
    )`
3. See the request fails with an empty error
4. ...

**Expected behavior**
auth token should be returned

**Context and environment**
Used inside lambda function on NodeJs environment

**Additional information**
Although in the documentation is specified that the parameters should be sent as x-form-urlencoded : https://apps.developer.monday.com/docs/oauth
<img width="834" alt="Screenshot 2022-08-03 at 21 05 28" src="https://user-images.githubusercontent.com/107402800/182678368-f03cf07e-631e-465a-ab65-2c69056869e4.png">
looks like the library itself is not respecting that and is using body as string :

```
await fetch.nodeFetch(url, {
    method: options.method || "POST",
    body: JSON.stringify(data || {}),
    headers: {
      Authorization: token,
      "Content-Type": "application/json"
    }
  });
```
in oauth-service.js

`execute(data, null, { url: MONDAY_OAUTH_TOKEN_URL });`

this method is invoked which uses inside body as string

this can be the issue probably...

**Comment by gregra81** [comment]
Hey @ionscorobogaci, is this still happening for you?

**Comment by gregra81** [comment]
Closing this as I assume this was solved. Feel free to open a new issue in case you encounter a similar behavior
