### ISSUE TITLE
[Bug] monday.set method doesn't honor parameters

### ISSUE THREAD

**Issue by MarvelProgramming** [mondaycom/monday-sdk-js#66]
**Describe the bug**
The monday.set method doesn't seem to use the params you supply it.

**Steps to reproduce**
1. Embed the SDK in an app
2. Call `monday.set('settings', { properties... })`
3. You can see in the request payload that the values you give to each property aren't present, and the defaults are used instead

**Expected behavior**
I expected the new settings to be applied to my app.

**Context and environment**
- I am using the monday.set method
- I am using Chrome as my browser
- The app is still in development, and the offending code can be seen [here](https://github.com/MarvJohnson/Green-Works/blob/main/src/services/monday.js#:~:text=*/-,export%20async%20function%20setMondaySettings(newSettings)%20%7B,%7D,-export%20async%20function) or in one of the screenshots below

**Additional information**
Here are screenshots that may help provide clarity:

The function I've written that calls the monday.set method. The globalCardlockState, checkInReminder, teamGoal, teamMemberCount, and teamSuccessRate properties always have the same values shown in the image, regardless of what I pass into the method.

---

![code-for-updating-settings](https://user-images.githubusercontent.com/51891409/188727940-396e4a90-b2ae-4d75-994b-e5a2c8ec2457.PNG)

The request's payload.

---

![request-payload](https://user-images.githubusercontent.com/51891409/188727943-5bc1e484-ac9a-427a-a464-2b9de71de292.PNG)

A snippet of the monday.set method as shown in the README.

---

![sdk-method](https://user-images.githubusercontent.com/51891409/188727944-36c67c87-8697-4ea0-8a8d-880b1bb1f893.PNG)

**Comment by gregra81** [comment]
Hi @MarvelProgramming, is this still relevant?
