### ISSUE TITLE
Queries With Whitespace Cause Error in monday.api

### ISSUE THREAD

**Issue by charliejlevine** [mondaycom/monday-sdk-js#82]
**Describe the bug**
Calls to `monday.api` containing queries with whitespace began failing on March 29 at 6:00 a.m. EST.

**Steps to reproduce**
1. Embed the SDK in an app
2. Run the following code (sensitive info redacted).
```
monday.api(`mutation {
        create_item(
          board_id: ...,
          item_name: "...",
          column_values: "{
            \"date\" : {
              \"date\" : \"...\",
              \"time\" : \"...\"
            },
            \"numbers\": \"...\",
            \"long_text\": {
              \"text\" : \"...\\n...\"
            }
          }"
        ) {
          id
        }
      }`
)
```
3. See the request fails with an error (sensitive info redacted).
```
Parse error on bad Unicode escape sequence: "{\n            \\\"date\\\" : {\n              \\\"date\\\" : \\\"...\\\",\n              \\\"time\\\" : \\\"...\\\n            },\n            \\\"numbers\\\": \\\"...\\\"...}" (error) at [5, 26]"
```
4. Remove whitespace from the query to fix it (read the end for details).

**Expected behavior**
Before March 29 at 6:00 a.m. EST, queries with whitespace worked.

**Context and environment**
These calls are run routinely in a scheduled cloud function on the Google Cloud Platform.

**Solution**
Putting the query in a function that removes whitespace solved the issue.
```
const removeNewLines = (s: string) => {
  s = s.replace(/\s{2,}/g, ' ');
  s = s.replace(/\t/g, ' ');
  s = s
    .toString()
    .trim()
    .replace(/(\r\n|\n|\r)/g, '');
  return s;
};

monday.api(removeNewLines(`mutation...`)
```

**Comment by Spunkie** [comment]
Partially related: #35

**Comment by gregra81** [comment]
@Spunkie @charliejlevine after taking this with the api team, their recommendation is to not put unescaped new line characters in a JSON value inside a GraphQL query as a JS string. So there are two alternatives:

1. interpolate JSON.stringify({…}) - why create a JSON by hand and escape it manually if it could just be a regular JS object stringified into a JSON?
2. Use query variables - if you really want to write a JSON by hand, you can put it in a query variable (which is a regular JS object)

So something like this should do the trick:
```js
monday.api(
  `mutation CreateItem($boardId: ID!, $itemName: String!, $columnValues: JSON!) {
  create_item(
    board_id: $boardId,
    item_name: $itemName,
    column_values: $columnValues
  ) {
    id
  }
}`,
  {
    variables: {
      boardId,
      itemName,
      columnValues: JSON.stringify({
        date: {
          date: "...",
          time: "...",
        },
        numbers: "...",
        long_text: {
          text: "...n...",
        },
      }),
    },
  }
);

```

Hope it helps

**Comment by gregra81** [comment]
Closing this now, as I'm assuming this solves your problem
