### ISSUE TITLE
[Bug] monday.execute for 'openItemCard' does not resolve promise for kind 'updates'

### ISSUE THREAD

**Issue by fredunikoo** [mondaycom/monday-sdk-js#92]
**Describe the bug**
monday.execute for type 'openItemCard' returns a promise. There are 2 kinds possible: 'columns' or 'updates' (https://developer.monday.com/apps/docs/mondayexecute#open-item-card). When using the default 'columns' for kind the returned promise resolves correctly when the card is closed. when using 'updates' as kind, the promise never resolves nor rejects when closing the card.

**Steps to reproduce**
1. Embed the SDK in an app
2. Call `monday.execute('openItemCard', { itemId: item.id, kind: 'updates' })` and wait for the returned promise to resolve
3. Close the opened updates item card
4. The promise does not resolve nor reject

**Expected behavior**
The promise should resolve when closing the 'updates' item card.

**Context and environment**
Working with a custom view on a board, implemented as a react app. Using version 0.3.2 of monday-sdk-js (latest version at time of writing)

**Comment by gregra81** [comment]
@fredunikoo The issue has been solved, thank you for opening the issue
